---                                                                                  
- hosts: black_pearl
  vars:
    user_password: ansiuser
  tasks:
    - ansible.builtin.user:
        name: ansible
        password: "{{ user_password | password_hash('sha512','salt') }}"
        shell: /bin/bash
        create_home: true
        groups: "{{ admin_group }}"
      
      register: results

    - debug:
        var: results
