---
- hosts: all
  tasks: 

    - name: One
      ansible.builtin.unarchive:
        src: TestArchive.tar
        dest: /tmp

    - name: Two
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.99/bin/apache-tomcat-8.5.99.tar.gz
        dest: /opt
        remote_src: true
    
    - name: Three
      ansible.builtin.copy:
        src: TestArchive.tar
        dest: /home/admin/
        owner: admin
        group: admin

    - name: Four
      ansible.builtin.file:
        path: /home/admin/Archive
        state: directory
        mode: '0755'
        owner: admin
        group: admin

    - name: Four
      ansible.builtin.unarchive:
        src: /home/admin/TestArchive.tar
        dest: /home/admin/Archive
        owner: admin
        group: admin
        remote_src: yes