---
- name: Creating Storage Partition and lvm
  hosts: test
  vars:
    vg_name: test_vg
    lv_name: test

# Ensuring a block partition must be present 
  pre_tasks:
    - name: Creating block storage
      ansible.builtin.parted:
        device: /dev/sdb
        number: 1
        state: present
        part_end: 1GiB
        flags: [lvm ]

# Creating a volume group and lvm
  tasks:
    - name: Creating Volume Group 
      community.general.lvg:
        vg: "{{ vg_name }}"
        pvs: /dev/sdb1
      # pesize: 16
        state: present
              # absent
              # inactive
              # active
      # reset_vg_uuid: true/false

    # Creating LVM
    - name: Creating LVM 
      community.general.lvol:
        vg: "{{ vg_name }}"
        lv: "{{ lv_name }}"
        size: +100%FREE
        pvs: /dev/sdb1

# Formatting the partition and Mounting the storage  
  post_tasks:
    
    # Formatting a XFS filesystem 
    - name: Create a XFS filesystem of /dev/sdb1
      community.general.filesystem:
        fstype: xfs
        dev: "/dev/{{ vg_name }}/{{ lv_name }}"
        state: present
              # absent
    #   uuid: generate

    # mounting a volume
    - name: mounting a filesystem
      ansible.posix.mount:
        path: "/tmp/"
        src: "/dev/{{ vg_name }}/{{ lv_name }}"
        fstype: xfs
        state: present
              # present - volume will be mounted + /etc/fstab will be present
              # absent  - volume + /etc/fstab entry will be removed
              # mounted - volume will be mounted but not persistent across reboot
              # remounted - volume will be remounted
        opts: defaults
             # exec
        dump: 0
        passno: 0

    - ansible.posix.mount:
        path: "/tmp/"
        src: "/dev/{{ vg_name }}/{{ lv_name }}"
        fstype: xfs
        state: mounted

...