---
- name: Configure VS Code Repo
  hosts: test
  tasks:
    - ansible.builtin.rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - ansible.builtin.yum_repository:
        file: vscode
        name: "code"
        description: "Visual Studio Code"
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc

    - name: Installing VS Code
      ansible.builtin.dnf:
        name: code
        state: latest
