- hosts: db
  vars:
    users:
      - username: user1
        passwd: user1

      - username: user2
        passwd: user2

      - username: user3
        passwd: user3

      - username: user4
        passwd: user4

      - username: user5
        passwd: user5

      - username: user6
        passwd: user6

  tasks:
    - name: Creating Multiple Users
      ansible.builtin.user:
        name: "{{ item.username }}"
        password:   "{{ item.passwd | password_hash('sha512') }}"
        state: present
      with_items: "{{ users }}"
