############################ Defining Single Line Play ###################################

- name: Installing server packages # Name (Optional) Heading of a play (See Playbook-2.yaml)
  hosts: dev  # <host-pattern> hosts on which playbook will run
  tasks: # Play
    # Heading to a Module (not entire play)
    - name: Installing FTP # Task - 1 
    # Module: key=value key=value [See ansible-doc yum for more information]
      yum: name=ftp state=present # Module 1 
    
    - name: httpd install # Task - 2
      yum: name=httpd state=present # module 2
    
    - name: service start and enable # Task - 3
      service: name=httpd enabled=true state=started # module 3
